### ISSUE TITLE
We need few more colors for iterm2

### ISSUE THREAD

**Issue by roeniss** [dofuuz/dimidium#2]
Currently, dimidium offers 18 colors, 16 ANSI, foreground, and background.

But my iTerm2 uses more colors, including those 18:

```text
Badge
Bold
Cursor
Cursor Guide
Cursor Text
Link
Selected Text
Selection
```

I think these are not just for iTerm2 only

IMHO, if dimidium doesn't offer those colors it will hardly be used. Can you make those colors, too? 

*(I'd tried by myself but not was satisfied well)*

**Comment by dofuuz** [comment]
iTerm2 기본 Dark Background에서 색상 가져와서 조정 후 추가해봤습니다.

[dimidium.itermcolors.zip](https://github.com/dofuuz/dimidium/files/14267584/dimidium.itermcolors.zip)

제가 macOS 장비가 없어서 iTerm2는 테스트를 할수가 없습니다...  
첨부파일 적용하시고 
- Badge, Cursor Guide 적용한 상태에서
- 화면에 링크 포함
- 커서가 텍스트 위에 있고, 
- 텍스트를 일부 선택한 상황에서 

스크린샷 한 장 부탁드립니다.

**Comment by roeniss** [comment]
우선 도와주셔서 감사합니다!

제공해주신 파일에 `qq` 오타가 있어서, 제거하고 import 진행했습니다. 

---

![Screenshot 2024-02-15 at 00 49 14 by seonghyeok](https://github.com/dofuuz/dimidium/assets/26613280/772ba0a6-64c2-490b-8839-b341b9038cbf)

- 우상단에 보이는 것이 badge text

![Screenshot 2024-02-15 at 00 53 09 by seonghyeok](https://github.com/dofuuz/dimidium/assets/26613280/b3d915b1-1a0a-49a8-894b-0f74b6449dd9)

- 텍스트를 일부 선택한 상황

![Screenshot 2024-02-15 at 00 53 48 by seonghyeok](https://github.com/dofuuz/dimidium/assets/26613280/f1622372-d55c-47e9-86f9-a913014bd4ef)

- (제 세팅 때문인지 아닌지 잘 모르겠는데) **링크에 그냥 커서를 올린 것만으로는 따로 하이라이팅이 안되더군요.** 위 이미지는 cmd 키를 누른 상태로 커서를 링크 위에 올린 상황

![Screenshot 2024-02-15 at 00 54 35 by seonghyeok](https://github.com/dofuuz/dimidium/assets/26613280/be099b7a-08a7-41fd-afd9-ec9fd0b650f6)

- `cmd+/` 를 눌러 cursor guide 피쳐를 트리거한 상황

![Screenshot 2024-02-15 at 00 56 24 by seonghyeok](https://github.com/dofuuz/dimidium/assets/26613280/40fbde39-21d4-4c2d-a819-b2e624f12aed)

- `bat` 명령어를 통해 출력한 결과

뭔가 좀 다채로운 그림을 보여드리고 싶은데 이게 참 생각대로 잘 안되는군요... 저는 일단 만족이긴 합니다. 혹시 더 필요하신 이미지/gif 가 있을까요? @dofuuz

**Comment by dofuuz** [comment]
테스트 감사합니다😉
(bat의 경우, ANSI 16색이 아닌 bat 자체 색상 구성을 사용하기 때문에 Dimidium이 적용되지 않습니다.)
말씀해주신 오류 수정 및 색 추가 조정 후 커밋하도록 하겠습니다.

**Comment by dofuuz** [comment]
Selection, Cursor Guide, Badge, Link color acquired from iTerm Dark Background color scheme, then, adjusted.

https://colab.research.google.com/drive/1IyVmjkGJ2shkaRD-HSy76fpRInGPunBp?usp=sharing

![itermdimidium](https://github.com/dofuuz/dimidium/assets/8174871/0368a78c-2b85-4a0e-a230-202f16f45140)
